# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 14419a2fc9aa860247a9bc8312aaf31c70fda8394e215797d06dde3e6044a2e47481b3eb11233a99783a579340f5dafb28100663ed8faee1ebaf8c62f93ae880
  github_app_id: 2a0d281f84869dd7ddda
  github_app_secret: 244b1ca87e7a2c84621255408b5286790c87f845

test:
  secret_key_base: 30ec4fc2ab64a633587cef3c6e8d5df3294c22d64a60ab643dbd8296ff577d3bf7308baba1767450f11c643c8507f290f9eff4210761e34bdad404cf1c3856a5
  github_app_id: 2a0d281f84869dd7ddda
  github_app_secret: 244b1ca87e7a2c84621255408b5286790c87f845

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_app_id: <%= ENV["GITHUB_APP_ID"] %>
  github_app_secret: <%= ENV["GITHUB_APP_SECRET"] %>
